version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev"]

  user_service:
    build:
      context: ./backend/user-service
    ports:
      - "5000:5000"
    env_file:
      - ./backend/user-service/.env
    volumes:
      - ./backend/user-service:/app 
    command: ["npm", "run", "dev"] 
    environment:
      - NODE_ENV=development
    networks:
      - peerprep-network


  question_service:
    build:
      context: ./backend/question-service
    ports:
      - "5001:5001" 
    env_file:
      - ./backend/question-service/.env 
    volumes:
      - ./backend/question-service:/app  
    command: ["npm", "run", "dev"]  
    environment:
      - NODE_ENV=development
    networks:
      - peerprep-network

networks:
 peerprep-network:
   driver: bridge    